/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomProjectPage: typeof import('./src/components/CustomProjectPage.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    LanguageBar: typeof import('./src/components/LanguageBar.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StandardProjectPage: typeof import('./src/components/StandardProjectPage.vue')['default']
    TopicTree: typeof import('./src/components/TopicTree.vue')['default']
  }
}
